<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ChoiceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('choices')->insert(
            [
                [
                    'content' 	  	 => "1/3",
                    'status' 		 => "yes",
                    'question_id' 	 => 1,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "1/2",
                    'status' 		 => "no",
                    'question_id' 	 => 1,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "1/6",
                    'status' 		 => "no",
                    'question_id' 	 => 1,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "8 mètres",
                    'status' 		 => "no",
                    'question_id' 	 => 2,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "10 mètres",
                    'status' 		 => "no",
                    'question_id' 	 => 2,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "12 mètres",
                    'status' 		 => "yes",
                    'question_id' 	 => 2,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "600",
                    'status' 		 => "no",
                    'question_id' 	 => 3,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "620",
                    'status' 		 => "no",
                    'question_id' 	 => 3,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "700",
                    'status' 		 => "no",
                    'question_id' 	 => 3,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "720",
                    'status' 		 => "yes",
                    'question_id' 	 => 3,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "4x=0",
                    'status' 		 => "no",
                    'question_id' 	 => 4,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "5x=0",
                    'status' 		 => "yes",
                    'question_id' 	 => 4,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "5x=2",
                    'status' 		 => "no",
                    'question_id' 	 => 4,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "( -4x  + 17 )(x + 3)",
                    'status' 		 => "no",
                    'question_id' 	 => 5,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(-x + 2)( x + 1)",
                    'status' 		 => "yes",
                    'question_id' 	 => 5,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(2x +5)",
                    'status' 		 => "no",
                    'question_id' 	 => 5,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(x + 1)",
                    'status' 		 => "no",
                    'question_id' 	 => 5,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(x + 1)",
                    'status' 		 => "no",
                    'question_id' 	 => 5,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "droite",
                    'status' 		 => "no",
                    'question_id' 	 => 6,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "hyperbole",
                    'status' 		 => "no",
                    'question_id' 	 => 6,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "parabole",
                    'status' 		 => "yes",
                    'question_id' 	 => 6,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "décroissante",
                    'status' 		 => "yes",
                    'question_id' 	 => 7,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "croissante",
                    'status' 		 => "no",
                    'question_id' 	 => 7,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "constante",
                    'status' 		 => "no",
                    'question_id' 	 => 7,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "a² - 4ab + 4b²",
                    'status' 		 => "no",
                    'question_id' 	 => 8,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(a - 2b)²",
                    'status' 		 => "no",
                    'question_id' 	 => 8,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "a² - 2b²",
                    'status' 		 => "no",
                    'question_id' 	 => 8,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "a² - 4b²",
                    'status' 		 => "yes",
                    'question_id' 	 => 8,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2a(a - 1)",
                    'status' 		 => "no",
                    'question_id' 	 => 9,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "a(2a - 1)",
                    'status' 		 => "yes",
                    'question_id' 	 => 9,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "a(2a - a)",
                    'status' 		 => "no",
                    'question_id' 	 => 9,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "0",
                    'status' 		 => "no",
                    'question_id' 	 => 10,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "21",
                    'status' 		 => "no",
                    'question_id' 	 => 10,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "25",
                    'status' 		 => "yes",
                    'question_id' 	 => 10,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "-1",
                    'status' 		 => "yes",
                    'question_id' 	 => 11,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "-2",
                    'status' 		 => "no",
                    'question_id' 	 => 11,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "7/2",
                    'status' 		 => "yes",
                    'question_id' 	 => 11,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2",
                    'status' 		 => "no",
                    'question_id' 	 => 12,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "1",
                    'status' 		 => "no",
                    'question_id' 	 => 12,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "0",
                    'status' 		 => "yes",
                    'question_id' 	 => 12,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "D'Archimède",
                    'status' 		 => "no",
                    'question_id' 	 => 13,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "D'Euclide",
                    'status' 		 => "no",
                    'question_id' 	 => 13,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "D'Eratosthène",
                    'status' 		 => "yes",
                    'question_id' 	 => 13,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "24",
                    'status' 		 => "no",
                    'question_id' 	 => 14,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "25",
                    'status' 		 => "no",
                    'question_id' 	 => 14,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "21",
                    'status' 		 => "yes",
                    'question_id' 	 => 14,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "Paire",
                    'status' 		 => "no",
                    'question_id' 	 => 15,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "Impaire",
                    'status' 		 => "yes",
                    'question_id' 	 => 15,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "3.75",
                    'status' 		 => "yes",
                    'question_id' 	 => 16,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "4.40",
                    'status' 		 => "no",
                    'question_id' 	 => 16,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2.87",
                    'status' 		 => "no",
                    'question_id' 	 => 16,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "Une parabole de sommet 0, origine du répère.",
                    'status' 		 => "yes",
                    'question_id' 	 => 17,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "Une courbe comme les autres.",
                    'status' 		 => "no",
                    'question_id' 	 => 17,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "Une hyperbole de sommet 0 origine du repère",
                    'status' 		 => "no",
                    'question_id' 	 => 17,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "22 ans",
                    'status' 		 => "yes",
                    'question_id' 	 => 18,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "17 ans",
                    'status' 		 => "no",
                    'question_id' 	 => 18,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "14 ans",
                    'status' 		 => "no",
                    'question_id' 	 => 18,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "58 secondes",
                    'status'         => "yes",
                    'question_id'    => 19,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "60 secondes",
                    'status'         => "no",
                    'question_id'    => 19,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "57 secondes",
                    'status'         => "no",
                    'question_id'    => 19,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "43%",
                    'status' 		 => "no",
                    'question_id' 	 => 20,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "44%",
                    'status' 		 => "no",
                    'question_id' 	 => 20,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "45%",
                    'status' 		 => "yes",
                    'question_id' 	 => 20,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "46%",
                    'status' 		 => "no",
                    'question_id' 	 => 20,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "6 jours 19 heures 38 minutes 5 secondes",
                    'status' 		 => "no",
                    'question_id' 	 => 21,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "6 jours 19 heures 37 minutes 5 secondes",
                    'status' 		 => "no",
                    'question_id' 	 => 21,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "6 jours 20 heures 37 minutes 5 secondes",
                    'status' 		 => "no",
                    'question_id' 	 => 21,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "6 jours 20 heures 38 minutes 5 secondes",
                    'status' 		 => "yes",
                    'question_id' 	 => 21,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "3",
                    'status' 		 => "no",
                    'question_id' 	 => 22,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "11",
                    'status' 		 => "no",
                    'question_id' 	 => 22,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "13",
                    'status' 		 => "no",
                    'question_id' 	 => 22,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "17",
                    'status' 		 => "yes",
                    'question_id' 	 => 22,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "9 barres",
                    'status' 		 => "no",
                    'question_id' 	 => 23,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "11 barres",
                    'status' 		 => "no",
                    'question_id' 	 => 23,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "12 barres",
                    'status' 		 => "no",
                    'question_id' 	 => 23,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "13 barres",
                    'status' 		 => "no",
                    'question_id' 	 => 23,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "x < - 8",
                    'status' 		 => "yes",
                    'question_id' 	 => 24,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "x > - 8",
                    'status' 		 => "no",
                    'question_id' 	 => 24,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "x < 8",
                    'status' 		 => "no",
                    'question_id' 	 => 24,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "x > 8",
                    'status' 		 => "no",
                    'question_id' 	 => 24,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2,997 925. 10e7 m/s",
                    'status' 		 => "no",
                    'question_id' 	 => 25,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2,997 925 .10e6 km/s",
                    'status' 		 => "no",
                    'question_id' 	 => 25,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2,997 925 . 10e8 m/s",
                    'status' 		 => "yes",
                    'question_id' 	 => 26,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2,997 925 . 10e4 km/s",
                    'status' 		 => "no",
                    'question_id' 	 => 25,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "1",
                    'status' 		 => "no",
                    'question_id' 	 => 26,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "2",
                    'status' 		 => "no",
                    'question_id' 	 => 26,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "4.5",
                    'status' 		 => "yes",
                    'question_id' 	 => 26,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "5",
                    'status' 		 => "no",
                    'question_id' 	 => 26,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "3X² +2X + 1",
                    'status' 		 => "no",
                    'question_id' 	 => 27,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "5X² – X + 1",
                    'status' 		 => "no",
                    'question_id' 	 => 27,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(X – 1) (5X + 8)",
                    'status' 		 => "yes",
                    'question_id' 	 => 27,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content' 	  	 => "(3X – 5) (X + 2)",
                    'status' 		 => "no",
                    'question_id' 	 => 27,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "C'est un symbole représentant l'infini",
                    'status'         => "yes",
                    'question_id'    => 28,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "C'est un symbole représentant le nombre Phi",
                    'status'         => "no",
                    'question_id'    => 28,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "Ce symbole est connu depuis l'antiquité",
                    'status'         => "yes",
                    'question_id'    => 28,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "Le mot Lemniscate signifie ruban en latin",
                    'status'         => "yes",
                    'question_id'    => 28,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                  [
                    'content'        => "Elle a été inventée par Einstein",
                    'status'         => "yes",
                    'question_id'    => 29,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "Elle a été inventée par Isaac Nweton",
                    'status'         => "no",
                    'question_id'    => 29,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "Le E de l'équation signifie Equation",
                    'status'         => "yes",
                    'question_id'    => 29,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
                [
                    'content'        => "Le E de l'équation signifie Energie",
                    'status'         => "yes",
                    'question_id'    => 29,
                    'created_at'     => Carbon::now(),
                    'updated_at'     => Carbon::now(),
                ],
            ]
        );
    }
}
